import type { Article } from "$lib/data";

export const articles: Article[] = [
    {
        id: '02-digital_cable-01',
        cat: '02-digital_cable',
        path: '/blog/02-digital_cable/log1',
        title: '1.デジタル信号とは',
        ath: '02',
        date: '2026-03-04',
        index: 1,
    },
    {
        id: '02-digital_cable-02',
        cat: '02-digital_cable',
        path: '/blog/02-digital_cable/log2',
        title: '2.デジタル信号の用途',
        ath: '02',
        date: '2026-03-04',
        index: 2,
    },
    {
        id: '02-digital_cable-03',
        cat: '02-digital_cable',
        path:  '/blog/02-digital_cable/log3',
        title: '3.映像を伝えるケーブル①',
        ath: '02',
        date: '2026-03-04',
        index: 3,
    },
    {
        id: '02-digital_cable-04',
        cat: '02-digital_cable',
        path:  '/blog/02-digital_cable/log4',
        title: '4.映像を伝えるケーブル②',
        ath: '02',
        date: '2026-03-04',
        index: 4,
    },
    {
        id: '02-digital_cable-05',
        cat: '02-digital_cable',
        path:  '/blog/02-digital_cable/log5',
        title: '5.ネットワークを作るケーブル',
        ath: '02',
        date: '2026-03-04',
        index: 5,
    },
    {
        id: '02-digital_cable-06',
        cat: '02-digital_cable',
        path: '/blog/02-digital_cable/log6',
        title: '6.パソコンと周辺機器を繋ぐケーブル①',
        ath: '02',
        date: '2026-03-04',
        index: 6,
    },
    {
        id: '02-digital_cable-07',
        cat: '02-digital_cable',
        path: '/blog/02-digital_cable/log7',
        title: '7.パソコンと周辺機器を繋ぐケーブル②',
        ath: '02',
        date: '2026-03-04',
        index: 7,
    },
    {
        id: '02-digital_cable-08',
        cat: '02-digital_cable',
        path: '/blog/02-digital_cable/log8',
        title: '8.充電するためのケーブル',
        ath: '02',
        date: '2026-03-06',
        index: 8,
    },
    {
        id: '02-digital_cable-09',
        cat: '02-digital_cable',
        path: '/blog/02-digital_cable/log9',
        title: '9.複雑化したUSB規格',
        ath: '02',
        date: '2026-03-07',
        index: 9,
    },
    {
        id: '02-digital_cable-10',
        cat: '02-digital_cable',
        path: '/blog/02-digital_cable/log10',
        title: '10.USBハブの役割',
        ath: '02',
        date: '2026-03-08',
        index: 10,
    },
    {
        id: '02-digital_cable-11',
        cat: '02-digital_cable',
        path: '/blog/02-digital_cable/log11',
        title: '11.HDMI分配器',
        ath: '02',
        date: '2026-03-08',
        index: 11,
    },
    {
        id: '02-digital_cable-12',
        cat: '02-digital_cable',
        path: '/blog/02-digital_cable/log12',
        title: '12.キャプチャーボードとATEM',
        ath: '02',
        date: '2026-03-08',
        index: 12,
    },
    {
        id: '02-digital_cable-13',
        cat: '02-digital_cable',
        path: '/blog/02-digital_cable/log13',
        title: '13.映像信号をLANケーブルで伝える',
        ath: '02',
        date: '2026-03-08',
        index: 13,
    },
    {
        id: '02-digital_cable-14',
        cat: '02-digital_cable',
        path: '/blog/02-digital_cable/exercises',
        title: '演習問題',
        ath: '02',
        date: '2026-04-08',
        index: 14,
    },
];