import type { Article } from "$lib/data";

export const articles: Article[] = [
    //この配列を、記事のリストにする
    {
        id: '02-obs_studio-01',
        cat: '02-obs_studio',
        path: '/blog/02-obs_studio/01-install',
        title: '1.OBS Studioのインストール',
        ath: '02',
        date: '2026-04-12',
        index: 1,
    },
    {
        id: '02-obs_studio-02',
        cat: '02-obs_studio',
        path: '/blog/02-obs_studio/02-add-sources',
        title: '2.ソースの追加',
        ath: '02',
        date: '2026-04-12',
        index: 2,
    },
    {
        id: '02-obs_studio-03',
        cat: '02-obs_studio',
        path: '/blog/02-obs_studio/03-play-sound',
        title: '3.音声を再生する',
        ath: '02',
        date: '2026-04-12',
        index: 3,
    },
    {
        id: '02-obs_studio-04',
        cat: '02-obs_studio',
        path: '/blog/02-obs_studio/04-add-scenes',
        title: '4.シーンの追加',
        ath: '02',
        date: '2026-04-12',
        index: 4,
    },
    {
        id: '02-obs_studio-05',
        cat: '02-obs_studio',
        path: '/blog/02-obs_studio/05-studio-mode',
        title: '5.スタジオモード',
        ath: '02',
        date: '2026-04-12',
        index: 5,
    },
    {
        id: '02-obs_studio-06',
        cat: '02-obs_studio',
        path: '/blog/02-obs_studio/06-external-display',
        title: '6.外部ディスプレイに表示',
        ath: '02',
        date: '2026-04-12',
        index: 6,
    },
    {
        id: '02-obs_studio-07',
        cat: '02-obs_studio',
        path: '/blog/02-obs_studio/07-recording',
        title: '7.録画',
        ath: '02',
        date: '2026-04-12',
        index: 7,
    },
    {
        id: '02-obs_studio-08',
        cat: '02-obs_studio',
        path: '/blog/02-obs_studio/08-video-capture-device',
        title: '8.映像キャプチャデバイス',
        ath: '02',
        date: '2026-04-13',
        index: 8,
    },
];